package de.netprojectev.networking;

public enum OpCode {

	/*
	 * Client to Server
	 */
	CTS_ADD_COUNTDOWN,
	CTS_ADD_IMAGE_FILE,
	CTS_ADD_THEMESLIDE,
	CTS_REMOVE_MEDIA_FILE,
	CTS_EDIT_MEDIA_FILE,
	CTS_QUEUE_MEDIA_FILE,
	CTS_SHOW_MEDIA_FILE,
	CTS_SHOW_PREVIOUS_MEDIA_FILE(false),
	CTS_SHOW_NEXT_MEDIA_FILE(false),
	CTS_DEQUEUE_MEDIAFILE,
	CTS_ADD_VIDEO_FILE_START(false),
	CTS_ADD_VIDEO_FILE_DATA,
	CTS_ADD_VIDEO_FILE_FINISH(false),

	CTS_ADD_LIVE_TICKER_ELEMENT,
	CTS_REMOVE_LIVE_TICKER_ELEMENT,
	CTS_EDIT_LIVE_TICKER_ELEMENT,
	CTS_ENABLE_LIVE_TICKER(false),
	CTS_DISABLE_LIVE_TICKER(false),

	CTS_ADD_PRIORITY,
	CTS_ADD_THEME,
	CTS_REMOVE_PRIORITY,
	CTS_REMOVE_THEME,

	CTS_DISABLE_AUTO_MODE(false),
	CTS_ENABLE_AUTO_MODE(false),
	CTS_ENABLE_FULLSCREEN(false),
	CTS_DISABLE_FULLSCREEN(false),

	CTS_LOGIN_REQUEST,
	CTS_DISCONNECT,
	CTS_REQUEST_FULL_SYNC(false),
	CTS_RESET_SHOW_COUNT,

	CTS_REQUEST_SERVER_SHUTDOWN(false),
	CTS_HEARTBEAT_ACK(false),
	CTS_PROPERTY_UPDATE,

	/*
	 * Server to Client
	 */
	STC_SERVER_SHUTDOWN(false),
	STC_LOGIN_DENIED,
	STC_CONNECTION_ACK(false),

	STC_RESET_SHOW_COUNT_ACK,
	STC_ADD_MEDIA_FILE_ACK,
	STC_REMOVE_MEDIA_FILE_ACK,
	STC_EDIT_MEDIA_FILE_ACK,
	STC_QUEUE_MEDIA_FILE_ACK,
	STC_DEQUEUE_MEDIAFILE_ACK,
	STC_SHOW_MEDIA_FILE_ACK,

	STC_ADD_LIVE_TICKER_ELEMENT_ACK,
	STC_REMOVE_LIVE_TICKER_ELEMENT_ACK,
	STC_EDIT_LIVE_TICKER_ELEMENT_ACK,
	STC_ENABLE_LIVE_TICKER_ACK(false),
	STC_DISABLE_LIVE_TICKER_ACK(false),

	STC_ADD_PRIORITY_ACK,
	STC_ADD_THEME_ACK,
	STC_REMOVE_PRIORITY_ACK,
	STC_REMOVE_THEME_ACK,

	STC_ENABLE_AUTO_MODE_ACK(false),
	STC_DISABLE_AUTO_MODE_ACK(false),
	STC_ENABLE_FULLSCREEN_ACK(false),
	STC_DISABLE_FULLSCREEN_ACK(false),
	STC_FULL_SYNC_START(false),
	STC_FULL_SYNC_STOP(false),
	STC_TIMELEFT_SYNC,
	STC_HEARTBEAT_REQUEST(false),
	STC_INIT_PROPERTIES,
	STC_FORCE_RECONNECT(false),
	STC_PROPERTY_UPDATE_ACK;

	private final boolean dataContained;

	private OpCode() {
		this.dataContained = true;
	}

	private OpCode(boolean dataContained) {
		this.dataContained = dataContained;
	}

	public boolean isDataContained() {
		return this.dataContained;
	}
}
