package de.netprojectev.networking;

public enum OpCode {

	/*
	 * Client to Server
	 */
	ADD_MEDIA_FILE, 
	REMOVE_MEDIA_FILE, 
	EDIT_MEDIA_FILE, 
	QUEUE_MEDIA_FILE, 
	SHOW_MEDIA_FILE, 
	SHOW_PREVIOUS_MEDIA_FILE, 
	SHOW_NEXT_MEDIA_FILE, 

	ADD_LIVE_TICKER_ELEMENT, 
	REMOVE_LIVE_TICKER_ELEMENT,
	EDIT_LIVE_TICKER_ELEMENT,
	TOGGLE_LIVE_TICKER_START,
	
	ADD_PRIORITY, 
	ADD_THEME,
	REMOVE_PRIORITY,
	REMOVE_THEME,
	
	TOGGLE_AUTO_MODE, 
	TOGGLE_FULLSCREEN,
	
	LOGIN_REQUEST,
	DISCONNECT,
	
	
	
	/*
	 *  Server to Client TODO not used yet (implement the message handlers client sided)
	 */
	SERVER_SHUTDOWN,
	CONNECTION_ACK;
	
	
}
