package de.netprojectev.networking;

public enum OpCode {

	ADD_MEDIA_FILE, 
	REMOVE_MEDIA_FILE, 
	EDIT_MEDIA_FILE, 
	
	SHOW_MEDIA_FILE, 
	SHOW_PREVIOUS_MEDIA_FILE, 
	SHOW_NEXT_MEDIA_FILE,
	
	TOGGLE_AUTO_MODE, 
	TOGGLE_SHUFFLE_MODE, 
	
	ADD_PRIORITY, 
	ADD_THEME, 
	ADD_LIVE_TICKER_ELEMENT, 
	
	REMOVE_LIVE_TICKER_ELEMENT,
	EDIT_LIVE_TICKER_ELEMENT, 
	CONNECTION_ACK;
	
}
