/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.netprojectev.GUI.Preferences;

import java.awt.FileDialog;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;

import de.netprojectev.GUI.Manager.ManagerFrame;
import de.netprojectev.Media.Priority;
import de.netprojectev.Media.Theme;
import de.netprojectev.Misc.Constants;
import de.netprojectev.Misc.Misc;
import de.netprojectev.Preferences.PreferencesHandler;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * GUI main class of preferences.
 * handles all user changes on the preferences
 * @author samu
 */
public class PreferencesFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = -5332162076303310401L;
	
	private PreferencesHandler preferenceshandler;
	private Priority selectedPrio;
	private Theme selectedTheme;
	private ManagerFrame managerFrame;
	private File selectedImage;
	
	private FileDialog fd;

	/**
	 * 
	 * @param managerFrame the ManagerFrame it operates with.
	 */
    public PreferencesFrame(ManagerFrame managerFrame) {
    	
    	this.managerFrame = managerFrame;
    	this.preferenceshandler = PreferencesHandler.getInstance(); 
    	preferenceshandler.setPreferencesFrame(this);
    	preferenceshandler.setManagerFrame(managerFrame);
        initComponents();
        setLocation(Misc.currentMousePosition());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTabMain = new javax.swing.JPanel();
        jButtonReset = new javax.swing.JButton();
        jLabelTickerSpeed = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPreviewWidth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanelTabPrio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPrio = new javax.swing.JList();
        jLabelPrioName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrioName = new javax.swing.JTextField();
        jTextFieldPrioMin = new javax.swing.JTextField();
        jButtonPrioSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddPrio = new javax.swing.JButton();
        btnRemovePrio = new javax.swing.JButton();
        jPanelTabTheme = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTheme = new javax.swing.JList();
        jLabelThemeName = new javax.swing.JLabel();
        jLabelThemeBg = new javax.swing.JLabel();
        jTextFieldThemeName = new javax.swing.JTextField();
        jTextFieldThemeBgImg = new javax.swing.JTextField();
        btnSaveTheme = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnAddTheme = new javax.swing.JButton();
        btnRemoveTheme = new javax.swing.JButton();
        jButtonChooseBgImage = new javax.swing.JButton();
        jPanelThemeslideCreator = new javax.swing.JPanel();
        jButtonCancelPrefs = new javax.swing.JButton();
        jButtonApplyPrefs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jButtonReset.setText("Reset all data");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabelTickerSpeed.setText("Ticker Speed");

        jLabel1.setText("Preview width");

        jTextFieldPreviewWidth.setText(Integer.toString(preferenceshandler.getPreviewWidth()));

        jLabel3.setText("px");

        javax.swing.GroupLayout jPanelTabMainLayout = new javax.swing.GroupLayout(jPanelTabMain);
        jPanelTabMain.setLayout(jPanelTabMainLayout);
        jPanelTabMainLayout.setHorizontalGroup(
            jPanelTabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonReset))
                    .addGroup(jPanelTabMainLayout.createSequentialGroup()
                        .addGroup(jPanelTabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTickerSpeed)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelTabMainLayout.createSequentialGroup()
                                .addComponent(jTextFieldPreviewWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)))
                        .addGap(0, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTabMainLayout.setVerticalGroup(
            jPanelTabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPreviewWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanelTabMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTabMainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelTickerSpeed)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jButtonReset)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Main", jPanelTabMain);

        jListPrio.setModel(new PriorityListModel());
        jListPrio.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    listPrioritySelectionChanged();
                }
            }
        );
        jScrollPane1.setViewportView(jListPrio);

        jLabelPrioName.setText("Name");

        jLabel2.setText("Minutes");

        jButtonPrioSave.setText("Save");
        jButtonPrioSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrioSaveActionPerformed(evt);
            }
        });

        btnAddPrio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/netprojectev/GFX/plus_2.png"))); // NOI18N
        btnAddPrio.setToolTipText("Add new Priority.");
        btnAddPrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrioActionPerformed(evt);
            }
        });

        btnRemovePrio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/netprojectev/GFX/delete_2.png"))); // NOI18N
        btnRemovePrio.setToolTipText("Delete selected priority");
        btnRemovePrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePrioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabPrioLayout = new javax.swing.GroupLayout(jPanelTabPrio);
        jPanelTabPrio.setLayout(jPanelTabPrioLayout);
        jPanelTabPrioLayout.setHorizontalGroup(
            jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabPrioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(jPanelTabPrioLayout.createSequentialGroup()
                        .addGroup(jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTabPrioLayout.createSequentialGroup()
                                .addComponent(btnAddPrio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemovePrio))
                            .addGroup(jPanelTabPrioLayout.createSequentialGroup()
                                .addGroup(jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelPrioName, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(56, 56, 56)
                                .addGroup(jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrioName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonPrioSave))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTabPrioLayout.setVerticalGroup(
            jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabPrioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabPrioLayout.createSequentialGroup()
                        .addGroup(jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrioName)
                            .addComponent(jTextFieldPrioName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldPrioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jButtonPrioSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(jPanelTabPrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemovePrio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddPrio, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Priority", jPanelTabPrio);

        jListTheme.setModel(new ThemeListModel());
        jListTheme.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    listThemeSelectionChanged();
                }
            }
        );
        jScrollPane2.setViewportView(jListTheme);

        jLabelThemeName.setText("Name");

        jLabelThemeBg.setText("Background");

        btnSaveTheme.setText("Save");
        btnSaveTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveThemeActionPerformed(evt);
            }
        });

        btnAddTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/netprojectev/GFX/plus_2.png"))); // NOI18N
        btnAddTheme.setToolTipText("Add new theme.");
        btnAddTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddThemeActionPerformed(evt);
            }
        });

        btnRemoveTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/netprojectev/GFX/delete_2.png"))); // NOI18N
        btnRemoveTheme.setToolTipText("Delete selected theme.");
        btnRemoveTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveThemeActionPerformed(evt);
            }
        });

        jButtonChooseBgImage.setText("Choose");
        jButtonChooseBgImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseBgImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabThemeLayout = new javax.swing.GroupLayout(jPanelTabTheme);
        jPanelTabTheme.setLayout(jPanelTabThemeLayout);
        jPanelTabThemeLayout.setHorizontalGroup(
            jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanelTabThemeLayout.createSequentialGroup()
                        .addGroup(jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTabThemeLayout.createSequentialGroup()
                                .addComponent(btnAddTheme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveTheme))
                            .addGroup(jPanelTabThemeLayout.createSequentialGroup()
                                .addGroup(jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelThemeName)
                                    .addComponent(jLabelThemeBg))
                                .addGap(23, 23, 23)
                                .addGroup(jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldThemeName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldThemeBgImg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonChooseBgImage))
                            .addComponent(btnSaveTheme))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTabThemeLayout.setVerticalGroup(
            jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTabThemeLayout.createSequentialGroup()
                        .addGroup(jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelThemeName)
                            .addComponent(jTextFieldThemeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelThemeBg)
                            .addComponent(jTextFieldThemeBgImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonChooseBgImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addGroup(jPanelTabThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoveTheme, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddTheme, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Theme", jPanelTabTheme);

        javax.swing.GroupLayout jPanelThemeslideCreatorLayout = new javax.swing.GroupLayout(jPanelThemeslideCreator);
        jPanelThemeslideCreator.setLayout(jPanelThemeslideCreatorLayout);
        jPanelThemeslideCreatorLayout.setHorizontalGroup(
            jPanelThemeslideCreatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        jPanelThemeslideCreatorLayout.setVerticalGroup(
            jPanelThemeslideCreatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Themeslide Creator", jPanelThemeslideCreator);

        jButtonCancelPrefs.setText("Cancel");
        jButtonCancelPrefs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelPrefsActionPerformed(evt);
            }
        });

        jButtonApplyPrefs.setText("Apply");
        jButtonApplyPrefs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyPrefsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelPrefs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonApplyPrefs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelPrefs)
                    .addComponent(jButtonApplyPrefs))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonCancelPrefsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelPrefsActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelPrefsActionPerformed

    /**
     * preparing the fields to add a new priority and clearing list selection
     * @param evt
     */
    private void btnAddPrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrioActionPerformed
    	
    	selectedPrio = null;
    	jTextFieldPrioName.setText("New Priority");
    	jTextFieldPrioMin.setText("5");	
    	jListPrio.clearSelection();
    	
    }//GEN-LAST:event_btnAddPrioActionPerformed

    /**
     * preparing the fields to add a new priority and clearing list selection
     * @param evt
     */
    private void btnAddThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddThemeActionPerformed
    	selectedTheme = null;
    	jTextFieldThemeName.setText("New Theme");
    	jTextFieldThemeBgImg.setText("-");
    	jListTheme.clearSelection();
    }//GEN-LAST:event_btnAddThemeActionPerformed

    /**
     * handling the editing/saving of the current selected or a new priority
     * @param evt
     */
    private void jButtonPrioSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrioSaveActionPerformed
        
    	Boolean alreadyExists = false;
    	
    	if(selectedPrio == null) { //Creation of new Priority
    		if(!jTextFieldPrioName.getText().isEmpty() && !jTextFieldPrioMin.getText().isEmpty()) {
        		
        		for(int i = 0; i < preferenceshandler.getListOfPriorities().size(); i++) {
        			
        			if(preferenceshandler.getListOfPriorities().get(i).getName().equals(jTextFieldPrioName.getText())) {
        				alreadyExists = true;
        			}

        		}
        		
        		if(!alreadyExists) {
        			Priority newPriority = new Priority(jTextFieldPrioName.getText(), Integer.parseInt(jTextFieldPrioMin.getText()));
                	preferenceshandler.addPriority(newPriority);
                	jListPrio.setSelectedIndex(preferenceshandler.getListOfPriorities().size() - 1);
        		} else {
        			JOptionPane.showMessageDialog(this, "A priority with this name already exists.", "Error", JOptionPane.ERROR_MESSAGE);
        		}
        		
        	}
    	} else { //Editing the selected Priority
    		if(!selectedPrio.getName().equals(preferenceshandler.getListOfPriorities().get(0).getName())) {
    			selectedPrio.setName(jTextFieldPrioName.getText());
    			try {
        			if(!jTextFieldPrioMin.getText().isEmpty()) {
        				selectedPrio.setMinutesToShow(Integer.parseInt(jTextFieldPrioMin.getText()));
        			}
    			} catch (NumberFormatException e) {
    			}
    		}
    		preferenceshandler.refreshPrioListModel();
    	}
    	
    	managerFrame.refreshComboBoxCellEditor();
    	
    }//GEN-LAST:event_jButtonPrioSaveActionPerformed

    /**
     * removes the selected priorities from the list and the preferences handler
     * @param evt
     */
    private void btnRemovePrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePrioActionPerformed
        
    	int[] selectedIndices = jListPrio.getSelectedIndices();
    	if(selectedIndices.length > 0) {
    		preferenceshandler.removePriorities(Misc.indexListToPriorities(selectedIndices));
    	}
    	
    }//GEN-LAST:event_btnRemovePrioActionPerformed

    /**
     * 
     * @param evt
     */
    private void jButtonApplyPrefsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyPrefsActionPerformed

    	try {
    		if(Integer.parseInt(jTextFieldPreviewWidth.getText()) != preferenceshandler.getPreviewWidth()) {
    			preferenceshandler.setPreviewWidth(Integer.parseInt(jTextFieldPreviewWidth.getText()));
    		}
    	} catch (NumberFormatException e) {
    		//e.printStackTrace();
    	}
        	
    	
    	
    	dispose();
    }//GEN-LAST:event_jButtonApplyPrefsActionPerformed

    /**
     * opens a file dialog to let the user choose a file from disk as background image for the selected/new theme
     * @param evt
     */
    private void jButtonChooseBgImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseBgImageActionPerformed
    	fd = new FileDialog(this, "Load Background", FileDialog.LOAD);
        fd.setMultipleMode(false);
        fd.setDirectory(System.getProperty("user.home"));
        fd.setLocation(Misc.currentMousePosition());
        fd.setVisible(true);
    	selectedImage = fd.getFiles()[0];
		jTextFieldThemeBgImg.setText(selectedImage.getAbsolutePath());
    }//GEN-LAST:event_jButtonChooseBgImageActionPerformed

    /**
     * handling the editing/saving of the current selected or a new theme
     * @param evt
     */
    private void btnSaveThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveThemeActionPerformed
    	    	
    	Boolean alreadyExists = false;
    	selectedImage = new File(jTextFieldThemeBgImg.getText());
    	
    	
    	if(selectedTheme == null) { //Creation of new Priority
    		if(!jTextFieldThemeName.getText().isEmpty() && selectedImage.exists()) {
        		
    			
	        	for(int i = 0; i < preferenceshandler.getListOfThemes().size(); i++) {
	        		
	        		if(preferenceshandler.getListOfThemes().get(i).getName().equals(jTextFieldThemeName.getText())) {
	        			System.out.println("if reached");
	        			alreadyExists = true;
	        		}
	
    			}
        		
        		if(!alreadyExists) {
        			Theme newTheme = new Theme(jTextFieldThemeName.getText(), selectedImage);
                	preferenceshandler.addTheme(newTheme);
                	jListTheme.setSelectedIndex(preferenceshandler.getListOfThemes().size() - 1);
        		} else {
        			JOptionPane.showMessageDialog(this, "A theme with this name already exists.", "Error", JOptionPane.ERROR_MESSAGE);        		}
        		
        	}
    	} else { //Editing the selected Theme
    		//TODO Filtering for image files (maybe better in the filedialog)
    		selectedTheme.setName(jTextFieldThemeName.getText());
    		if(selectedImage.exists()) {
    			selectedTheme.setBackgroundImage(selectedImage);	
    		} else {
    			JOptionPane.showMessageDialog(this, "File cannot be found on the hard disk.", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    		preferenceshandler.refreshThemeListModel();
    	}
    	
    }//GEN-LAST:event_btnSaveThemeActionPerformed

    /**
     * removes selected themes from list and preferences handler
     * @param evt
     */
    private void btnRemoveThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveThemeActionPerformed
    	
    	int[] selectedIndices = jListTheme.getSelectedIndices(); 	
    	if(selectedIndices.length > 0) {
    		preferenceshandler.removeThemes(Misc.indexListToThemes(selectedIndices));
    	}
    }//GEN-LAST:event_btnRemoveThemeActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
    	 int exit = JOptionPane.showConfirmDialog(this, "Are you sure you want to reset all data?", "Reset", JOptionPane.YES_NO_OPTION);
         if (exit == JOptionPane.YES_OPTION) {	
         	
     		File[] allFiles = new File(Constants.SAVE_PATH).listFiles();
     		if(allFiles != null) {
     			for(int i = 0; i < allFiles.length; i++) {
     				if(!allFiles[i].isDirectory()) {
     					allFiles[i].delete();
     				}
         		}
     			 int exit2 = JOptionPane.showConfirmDialog(this, "All data have been reset sucessfully.\nThe program have to be restarted. Do you want to restart now?", "Data reset", JOptionPane.YES_NO_OPTION);
     			 if(exit2 == JOptionPane.YES_OPTION) {
     				 try {
						Misc.restartApplication();
					} catch (URISyntaxException e) {
						
						e.printStackTrace();
					} catch (IOException e) {
						
						e.printStackTrace();
					}
     			 }
     		} else {
     			JOptionPane.showMessageDialog(this,
     				    "Error while deleting files.",
     				    "Error",
     				    JOptionPane.ERROR_MESSAGE);
     		}
     		
         }

    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * on selection change, updates the name and background image fields
     */
	private void listThemeSelectionChanged() {
		int viewRow = jListTheme.getSelectedIndex();
		if(viewRow >= 0) {
			selectedTheme = preferenceshandler.getListOfThemes().get(viewRow);
			jTextFieldThemeName.setText(selectedTheme.getName());
			jTextFieldThemeBgImg.setText(selectedTheme.getBackgroundImage().getAbsolutePath());
		}
	}

	/**
	 * on selection change, updates the name and minutes fields
	 */
	private void listPrioritySelectionChanged() {
		int viewRow = jListPrio.getSelectedIndex();
		if(viewRow >= 0) {
		    selectedPrio = preferenceshandler.getListOfPriorities().get(viewRow);
		    jTextFieldPrioName.setText(selectedPrio.getName());
		    jTextFieldPrioMin.setText(Integer.toString(selectedPrio.getMinutesToShow()));
		}
	}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreferencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreferencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreferencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreferencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PreferencesFrame(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrio;
    private javax.swing.JButton btnAddTheme;
    private javax.swing.JButton btnRemovePrio;
    private javax.swing.JButton btnRemoveTheme;
    private javax.swing.JButton btnSaveTheme;
    private javax.swing.JButton jButtonApplyPrefs;
    private javax.swing.JButton jButtonCancelPrefs;
    private javax.swing.JButton jButtonChooseBgImage;
    private javax.swing.JButton jButtonPrioSave;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPrioName;
    private javax.swing.JLabel jLabelThemeBg;
    private javax.swing.JLabel jLabelThemeName;
    private javax.swing.JLabel jLabelTickerSpeed;
    private javax.swing.JList jListPrio;
    private javax.swing.JList jListTheme;
    private javax.swing.JPanel jPanelTabMain;
    private javax.swing.JPanel jPanelTabPrio;
    private javax.swing.JPanel jPanelTabTheme;
    private javax.swing.JPanel jPanelThemeslideCreator;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldPreviewWidth;
    private javax.swing.JTextField jTextFieldPrioMin;
    private javax.swing.JTextField jTextFieldPrioName;
    private javax.swing.JTextField jTextFieldThemeBgImg;
    private javax.swing.JTextField jTextFieldThemeName;
    // End of variables declaration//GEN-END:variables

	public javax.swing.JList getjListPrio() {
		return jListPrio;
	}

	public void setjListPrio(javax.swing.JList jListPrio) {
		this.jListPrio = jListPrio;
	}

	public ManagerFrame getManagerFrame() {
		return managerFrame;
	}

	public void setManagerFrame(ManagerFrame managerFrame) {
		this.managerFrame = managerFrame;
	}
	
    public File getSelectedImage() {
		return selectedImage;
	}

	public void setSelectedImage(File selectedImage) {
		this.selectedImage = selectedImage;
	}

	public javax.swing.JList getjList2() {
		return jListTheme;
	}

	public void setjList2(javax.swing.JList jList2) {
		this.jListTheme = jList2;
	}

}
